Importing Libraries needed

In [101]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

Importing dataset

In [102]:
dataset = pd.read_csv('Breast Cancer Data.csv')


In [103]:
dataset.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [104]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   id                       569 non-null    int64  
 1   diagnosis                569 non-null    object 
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             5

In [105]:
dataset.isna().sum()

id                           0
diagnosis                    0
radius_mean                  0
texture_mean                 0
perimeter_mean               0
area_mean                    0
smoothness_mean              0
compactness_mean             0
concavity_mean               0
concave points_mean          0
symmetry_mean                0
fractal_dimension_mean       0
radius_se                    0
texture_se                   0
perimeter_se                 0
area_se                      0
smoothness_se                0
compactness_se               0
concavity_se                 0
concave points_se            0
symmetry_se                  0
fractal_dimension_se         0
radius_worst                 0
texture_worst                0
perimeter_worst              0
area_worst                   0
smoothness_worst             0
compactness_worst            0
concavity_worst              0
concave points_worst         0
symmetry_worst               0
fractal_dimension_worst      0
Unnamed:

In [106]:
X = dataset.iloc[:, 2:32].values
y = dataset.iloc[:, 1].values

Encoding Categorical values using Label Encoding 
A Label Encoder is used to convert labels into numeric form i.e. machine readable form

In [107]:

from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X_1 = LabelEncoder()
y = labelencoder_X_1.fit_transform(y)


Train Test Split

In [108]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)



Feature Scaling using Standard Scaler

In [109]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from time import time
t = time()

Random Forest

In [110]:
rfc = RandomForestClassifier()
rfc.fit(X_train, y_train)
output = rfc.predict(X_test)
accuracy = accuracy_score(y_test, output) 
print("The accuracy of testing data: ",accuracy)
print("The running time: ",time()-t)

The accuracy of testing data:  0.9736842105263158
The running time:  0.8795151710510254


In [111]:
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y_test,output)
print("Confusion Matrix:\n",confusion_matrix)
from sklearn.metrics import classification_report
print("\nClassification Report:\n",classification_report(y_test, output))

Confusion Matrix:
 [[66  1]
 [ 2 45]]

Classification Report:
               precision    recall  f1-score   support

           0       0.97      0.99      0.98        67
           1       0.98      0.96      0.97        47

    accuracy                           0.97       114
   macro avg       0.97      0.97      0.97       114
weighted avg       0.97      0.97      0.97       114



**Bagging**

Bagging, also known as bootstrap aggregation, is the ensemble learning method that is commonly used to reduce variance within a noisy dataset. In bagging, a random sample of data in a training set is selected with replacement—meaning that the individual data points can be chosen more than once. After several data samples are generated, these weak models are then trained independently, and depending on the type of task—regression or classification, for example the average or majority of those predictions yield a more accurate estimate.

Bagging Classifier

In [112]:

from sklearn.ensemble import BaggingClassifier

In [113]:
bag = BaggingClassifier(n_estimators=50)
bag.fit(X_train, y_train)
output = bag.predict(X_test)
accuracy = accuracy_score(y_test, output) 
print("The accuracy of testing data: ",accuracy)
print("The running time: ",time()-t)

The accuracy of testing data:  0.956140350877193
The running time:  3.0861871242523193


In [114]:
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y_test,output)
print("Confusion Matrix:\n",confusion_matrix)
from sklearn.metrics import classification_report
print("\nClassification Report:\n",classification_report(y_test, output))

Confusion Matrix:
 [[64  3]
 [ 2 45]]

Classification Report:
               precision    recall  f1-score   support

           0       0.97      0.96      0.96        67
           1       0.94      0.96      0.95        47

    accuracy                           0.96       114
   macro avg       0.95      0.96      0.95       114
weighted avg       0.96      0.96      0.96       114



**Boosting**

Boosting is an ensemble modeling technique that attempts to build a strong classifier from the number of weak classifiers. It is done by building a model by using weak models in series. Firstly, a model is built from the training data. Then the second model is built which tries to correct the errors present in the first model. This procedure is continued and models are added until either the complete training data set is predicted correctly or the maximum number of models are added.

Gradient Boosting

In [115]:
from sklearn.ensemble import GradientBoostingClassifier

In [116]:
gbm = GradientBoostingClassifier(n_estimators=150,random_state=1)
gbm.fit(X_train, y_train)
output = gbm.predict(X_test)
accuracy = accuracy_score(y_test, output) 
print("The accuracy of testing data: ",accuracy)
print("The running time: ",time()-t)


The accuracy of testing data:  0.9824561403508771
The running time:  6.199452638626099


In [117]:
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y_test,output)
print("Confusion Matrix:\n",confusion_matrix)
from sklearn.metrics import classification_report
print("\nClassification Report:\n",classification_report(y_test, output))

Confusion Matrix:
 [[66  1]
 [ 1 46]]

Classification Report:
               precision    recall  f1-score   support

           0       0.99      0.99      0.99        67
           1       0.98      0.98      0.98        47

    accuracy                           0.98       114
   macro avg       0.98      0.98      0.98       114
weighted avg       0.98      0.98      0.98       114



Light GBM

In [118]:

from lightgbm import  LGBMClassifier as lgb

In [119]:
lgb = LGBMClassifier(n_estimators=200,random_state=1).fit(X_train, y_train)
lgb.fit(X_train, y_train)
output = lgb.predict(X_test)
accuracy = accuracy_score(y_test, output) 
print("The accuracy of testing data: ",accuracy)
print("The running time: ",time()-t)


The accuracy of testing data:  0.9824561403508771
The running time:  7.198002338409424


In [120]:
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y_test,output)
print("Confusion Matrix:\n",confusion_matrix)
from sklearn.metrics import classification_report
print("\nClassification Report:\n",classification_report(y_test, output))

Confusion Matrix:
 [[67  0]
 [ 2 45]]

Classification Report:
               precision    recall  f1-score   support

           0       0.97      1.00      0.99        67
           1       1.00      0.96      0.98        47

    accuracy                           0.98       114
   macro avg       0.99      0.98      0.98       114
weighted avg       0.98      0.98      0.98       114



XGB

In [121]:
from xgboost import XGBClassifier as xgb

In [122]:
xgb = XGBClassifier(n_estimators=100,random_state=1,eval_metric='mlogloss').fit(X_train, y_train)
xgb.fit(X_train, y_train)
output = xgb.predict(X_test)
accuracy = accuracy_score(y_test, output) 
print("The accuracy of testing data: ",accuracy)
print("The running time: ",time()-t)



The accuracy of testing data:  0.9824561403508771
The running time:  9.258988618850708


In [123]:
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y_test,output)
print("Confusion Matrix:\n",confusion_matrix)
from sklearn.metrics import classification_report
print("\nClassification Report:\n",classification_report(y_test, output))

Confusion Matrix:
 [[67  0]
 [ 2 45]]

Classification Report:
               precision    recall  f1-score   support

           0       0.97      1.00      0.99        67
           1       1.00      0.96      0.98        47

    accuracy                           0.98       114
   macro avg       0.99      0.98      0.98       114
weighted avg       0.98      0.98      0.98       114



**Stacking**

Stacking (a.k.a Stack Generalization) is an ensemble technique that uses meta-learning for generating predictions. It can harness the capabilities of well-performing as well as weakly-performing models on a classification or regression task and make predictions with better performance than any other single model in the ensemble.

It is an extended form of the Model Averaging Ensemble technique, where multiple sub-models contribute equally or according to their performance weights to a combined prediction. In Stacking, an entirely new model to trained to combine the contributions from each submodel and produce the best predictions. This final model is said to be stacked on top of the others, hence the name.

Level 1 Stack

In [124]:

from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier as knn
from sklearn.tree import DecisionTreeClassifier as dtc
from sklearn.ensemble import StackingClassifier
from sklearn.model_selection import cross_val_score

In [125]:

lf = [('xgb',XGBClassifier(n_estimators=400,random_state=1,eval_metric='mlogloss')),('rfc',RandomForestClassifier()),('knn',  KNeighborsClassifier()
)]
clf = StackingClassifier( estimators = lf,final_estimator = DecisionTreeClassifier())
t = time()
clf.fit(X_train, y_train)
output = clf.predict(X_test)
accuracy = accuracy_score(y_test, output) 
print("The accuracy of testing data: ",accuracy)
print("The running time: ",time()-t)

The accuracy of testing data:  0.9649122807017544
The running time:  4.741440057754517


In [126]:
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y_test,output)
print("Confusion Matrix:\n",confusion_matrix)
from sklearn.metrics import classification_report
print("\nClassification Report:\n",classification_report(y_test, output))

Confusion Matrix:
 [[67  0]
 [ 4 43]]

Classification Report:
               precision    recall  f1-score   support

           0       0.94      1.00      0.97        67
           1       1.00      0.91      0.96        47

    accuracy                           0.96       114
   macro avg       0.97      0.96      0.96       114
weighted avg       0.97      0.96      0.96       114

